### ISSUE TITLE
Übersicht Relaunch

### ISSUE THREAD

**Issue by fabianhauser** [altcomphsr/altcomphsr.vshsr.ch#1]
## Vier-Punkte-Plan <del>zur Weltherrschaft</del> zum Relaunch
1. Relaunch Webseite mit den Wichtigsten Inhalten des aktuellen Wikis
2. Restart Verein und übernahme Postfach
3. Rund-E-Mail HSR und Flyer & Quickstart Infrastruktur zum Studienstart vorbereiten
4. Alternative (Open Source) Software aufzeigen
### Ideen
- [x] Offene Kommunikation
- [x] Chat für Fragen / Probleme (-> IRC mit Webchat?)
- [x] Mailbox weiter betreiben (twitter-account?)
- [x] Verknüpfen, unterstützen Community / Open-Source-Projekte an der HSR ([Studenportal](https://studentenportal.ch/), OSM, [Python-Summit](http://www.python-summit.ch/), [VSHSR](http://www.vshsr.ch/), [HSR-Stud](https://hsr-stud.github.io/)  etc.  :arrow_right:  #13
- [x] Förderung Crypto (GPG etc.)?  :arrow_right:  #13
- [x] Einstiegshilfe LaTeX?  :arrow_right:  #13
- [x] Nur falls Nachfrage: Install Parties :arrow_right:  #13

**Comment by fabianhauser** [comment]
@michiwieland @raphiz @olidias: Habe in diesem Ticket mal unsere Besprechung zusammengefasst, falls was fehlt, einfach ergänzen!

**Comment by fabianhauser** [comment]
Dieses Issue kann geschlossen werden, da die Punkte umgesetzt oder in anderen Issues behandelt werden (siehe auch [altcomphsr/verein](https://github.com/altcomphsr/verein/issues))
